"""empty message

Revision ID: 1219c6d46fda
Revises: 14424c860fd6
Create Date: 2026-05-13 16:29:48.462020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1219c6d46fda'
down_revision: Union[str, Sequence[str], None] = '14424c860fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ativodb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ativodb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ativodb_ip'), ['ip'], unique=True)

    op.create_table('emaildb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emaildb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emaildb_endereco'), ['endereco'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emaildb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emaildb_endereco'))

    op.drop_table('emaildb')
    with op.batch_alter_table('ativodb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ativodb_ip'))

    op.drop_table('ativodb')
    # ### end Alembic commands ###
