"""empty message

Revision ID: 15eca5d1f87c
Revises: b52a44d30706
Create Date: 2026-05-22 16:01:52.109926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '15eca5d1f87c'
down_revision: Union[str, Sequence[str], None] = 'b52a44d30706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emaildb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emaildb_endereco'))

    op.drop_table('emaildb')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('email')

    op.create_table('emaildb',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('endereco', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emaildb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emaildb_endereco'), ['endereco'], unique=1)

    # ### end Alembic commands ###
