"""renomeando_tabela_setordb

Revision ID: 4dc6682e61c4
Revises: e939baf0c219
Create Date: 2026-05-14 20:40:25.600092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4dc6682e61c4'
down_revision: Union[str, Sequence[str], None] = 'e939baf0c219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupodb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grupodb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupodb_nome'), ['nome'], unique=True)

    with op.batch_alter_table('setordb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setordb_nome'))

    op.drop_table('setordb')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setordb',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=False),
    sa.Column('cor', sa.VARCHAR(), server_default=sa.text("'gray'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setordb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setordb_nome'), ['nome'], unique=1)

    with op.batch_alter_table('grupodb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupodb_nome'))

    op.drop_table('grupodb')
    # ### end Alembic commands ###
