"""empty message

Revision ID: 7b0d9b1fde25
Revises: 15eca5d1f87c
Create Date: 2026-05-28 15:22:03.863704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7b0d9b1fde25'
down_revision: Union[str, Sequence[str], None] = '15eca5d1f87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupodb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ininterrupto', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupodb', schema=None) as batch_op:
        batch_op.drop_column('ininterrupto')

    # ### end Alembic commands ###
