"""adicionando_coluna_nova

Revision ID: 9c3237f57fe6
Revises: 1219c6d46fda
Create Date: 2026-05-14 14:54:31.868181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9c3237f57fe6'
down_revision: Union[str, Sequence[str], None] = '1219c6d46fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setordb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setordb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setordb_nome'), ['nome'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setordb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setordb_nome'))

    op.drop_table('setordb')
    # ### end Alembic commands ###
