"""empty message

Revision ID: b52a44d30706
Revises: 4dc6682e61c4
Create Date: 2026-05-14 20:54:33.724433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b52a44d30706'
down_revision: Union[str, Sequence[str], None] = '4dc6682e61c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ativodb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'GERAL'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ativodb', schema=None) as batch_op:
        batch_op.drop_column('grupo')

    # ### end Alembic commands ###
