"""empty message

Revision ID: e939baf0c219
Revises: 9c3237f57fe6
Create Date: 2026-05-14 20:28:11.570649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e939baf0c219'
down_revision: Union[str, Sequence[str], None] = '9c3237f57fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setordb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'gray'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setordb', schema=None) as batch_op:
        batch_op.drop_column('cor')

    # ### end Alembic commands ###
